url: "http://maddyandmarvin2023.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Madeleine and Marvin's 2023 Wedding | Date TBC" # the name of your site, e.g. ACME Corp.
